test: check if `*.api.md` is up-to-date (#774)
<!--
  Thank you for submitting a pull request!

We appreciate the time and effort you have invested in making these
changes. Please ensure that you provide enough information to allow
others to review your pull request.

Upon submission, your pull request will be automatically assigned with
reviewers.

If you want to learn more about contributing to this project, please
visit:
https://github.com/lynx-family/lynx-stack/blob/main/CONTRIBUTING.md.
-->

## Summary

<!-- Can you explain the reasoning behind implementing this change? What
problem or issue does this pull request resolve? -->

Prevent future regressions similar to #751.

<!-- It would be helpful if you could provide any relevant context, such
as GitHub issues or related discussions. -->

## Checklist

<!--- Check and mark with an "x" -->

- [x] Tests updated (or not required).
- [ ] Documentation updated (or not required).

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -98,6 +98,30 @@ jobs:
         export ALL_ON_UI=true
         pnpm --filter @lynx-js/web-tests run test --reporter='github,dot,junit,html'
         pnpm --filter @lynx-js/web-tests run coverage:ci
+  test-api:
+    needs: build
+    uses: ./.github/workflows/workflow-test.yml
+    with:
+      runs-on: lynx-ubuntu-24.04-medium
+      run: |
+        pnpm turbo api-extractor -- --local
+        if test "$(git diff -- './packages/**/*.api.md' --name-only | wc -l)" -gt 0 ; then
+          echo "::error::API Report Changes Detected"
+          echo "The following API reports have changed:"
+          git diff -- './packages/**/*.api.md' --name-only
+          echo "::error::Please run 'turbo api-extractor -- --local' to update them."
+          echo ""
+          exit 1;
+        fi
+        git add --intent-to-add .
+        if test "$(git diff -- './packages/**/*.api.md' --name-only | wc -l)" -gt 0 ; then
+          echo "::error::API Report Changes Detected"
+          echo "The following API reports have changed:"
+          git diff -- './packages/**/*.api.md' --name-only
+          echo "::error::Please run 'turbo api-extractor -- --local' to update them."
+          echo ""
+          exit 1;
+        fi
   test-publish:
     needs: build
     uses: ./.github/workflows/workflow-test.yml
@@ -193,6 +217,7 @@ jobs:
       - code-style-check
       - playwright-linux
       - playwright-linux-all-on-ui
+      - test-api
       - test-publish
       - test-react
       - test-rust
